### ISSUE TITLE
New wavelet filters

### ISSUE THREAD

**Issue by KevinAquino** [epfl-lts2/gspbox#11]
Hiya,

I'm loving the toolbox! I was wondering if you had plans to add in different wavelet families like the Haar or daubechies wavelets?

**Comment by mdeff** [comment]
Thanks for your kind words. :) This toolbox is not actively developed anymore: There's little chance anything will be added. However, if you want to contribute, there are good chances your PRs will be accepted. Alternatively, I encourage you to look at the [python version](https://github.com/epfl-lts2/pygsp), which is actively developed.

**Comment by KevinAquino** [comment]
ah cool thanks! :)

**Comment by nperraud** [comment]
By the way, graph filters requires a continuous scaling and wavelet functions. So daubechies should work but Haar not.

In any case, it should be relatively trivial to defines daubechies both in the python and the matlab versions.

**Comment by mdeff** [comment]
For the PyGSP, could we use [PyWavelets](https://github.com/PyWavelets/pywt) instead of defining the wavelets ourselves?

**Comment by KevinAquino** [comment]
Thanks for the info! I might add in daubechies and send a PR :)

**Comment by mdeff** [comment]
Great! Looking forward. :)
