### ISSUE TITLE
gsp_isomap

### ISSUE THREAD

**Issue by jenniferrr** [epfl-lts2/gspbox#8]
Hello everyone,
In the following function: "gsp_isomap" you are using the "dijkstra" function hence it is not implemented in matlab! I tried to download one from MathWorks File Exchange but I found lots of functions!
Can you send me the right one?
Best regards and thanks in advance
Jennifer

**Comment by nperraud** [comment]
This function comes from the gaimc toolbox.

Just try to run `gsp_install` and see if there is any changes.
