### ISSUE TITLE
Querry related to GSP_TOOLBOX

### ISSUE THREAD

**Issue by AamerAshfaque** [epfl-lts2/gspbox#9]
Sir,
Please tell me about the variables input you have used for the program like 'G', 'F', 'param'.
If I already have the graph structure why do i need another signal f and what's this param. I will be highly obliged if you could help me with my doubts.

**Comment by mdeff** [comment]
Thanks for your interest. Note however that this toolbox is not developed nor maintained anymore. Please consider using the [pygsp](https://github.com/epfl-lts2/pygsp) instead. I recommend you to follow the [tutorials](https://pygsp.readthedocs.io/en/stable/tutorials/index.html) to get the basics.
